/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as DependencyRouteImport } from './routes/dependency'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcPathRouteImport } from './routes/api/trpc/$path'

const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const DependencyRoute = DependencyRouteImport.update({
  id: '/dependency',
  path: '/dependency',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcPathRoute = ApiTrpcPathRouteImport.update({
  id: '/api/trpc/$path',
  path: '/api/trpc/$path',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dependencies': typeof DependenciesRoute
  '/dependency': typeof DependencyRoute
  '/project': typeof ProjectRoute
  '/api/trpc/$path': typeof ApiTrpcPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dependencies': typeof DependenciesRoute
  '/dependency': typeof DependencyRoute
  '/project': typeof ProjectRoute
  '/api/trpc/$path': typeof ApiTrpcPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dependencies': typeof DependenciesRoute
  '/dependency': typeof DependencyRoute
  '/project': typeof ProjectRoute
  '/api/trpc/$path': typeof ApiTrpcPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dependencies'
    | '/dependency'
    | '/project'
    | '/api/trpc/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dependencies'
    | '/dependency'
    | '/project'
    | '/api/trpc/$path'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dependencies'
    | '/dependency'
    | '/project'
    | '/api/trpc/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DependenciesRoute: typeof DependenciesRoute
  DependencyRoute: typeof DependencyRoute
  ProjectRoute: typeof ProjectRoute
  ApiTrpcPathRoute: typeof ApiTrpcPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependency': {
      id: '/dependency'
      path: '/dependency'
      fullPath: '/dependency'
      preLoaderRoute: typeof DependencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$path': {
      id: '/api/trpc/$path'
      path: '/api/trpc/$path'
      fullPath: '/api/trpc/$path'
      preLoaderRoute: typeof ApiTrpcPathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DependenciesRoute: DependenciesRoute,
  DependencyRoute: DependencyRoute,
  ProjectRoute: ProjectRoute,
  ApiTrpcPathRoute: ApiTrpcPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
